### ISSUE TITLE
Klipper shutdown when calling {generate_shaper_x} or {generate_shaper_y}

### ISSUE THREAD

**Issue by bobbleheed** [lhndo/ResHelper#1]
I have tried reinstalling the plugin as well as making a clean mainsail install but there is no change. 
The following section is appearing in my klippy log which appears to be the issue:

```Resonances data written to /tmp/resonances_x_20230611_031039.csv file
Running Command {generate_shaper_x}...:
Stats 2653.7: gcodein=0  mcu: mcu_awake=0.002 mcu_task_avg=0.000009 mcu_task_stddev=0.000008 bytes_write=1229162 bytes_read=186553 bytes_retransmit=9 bytes_invalid=0 send_seq=22473 receive_seq=22473 retransmit_seq=2 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=100001586 z: mcu_awake=0.003 mcu_task_avg=0.000009 mcu_task_stddev=0.000008 bytes_write=81495 bytes_read=133770 bytes_retransmit=9 bytes_invalid=0 send_seq=5052 receive_seq=5052 retransmit_seq=2 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=100001506 adj=99999842 rpi: mcu_awake=0.001 mcu_task_avg=0.000013 mcu_task_stddev=0.000017 bytes_write=13266 bytes_read=2595399 bytes_retransmit=0 bytes_invalid=0 send_seq=1967 receive_seq=1967 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=49999145 adj=49998316  heater_bed: target=0 temp=20.7 pwm=0.000 raspberry_pi: temp=50.8 sysload=1.03 cputime=198.139 memavail=584588 print_time=576.473 buffer_time=0.000 print_stall=1 extruder: target=0 temp=20.1 pwm=0.000
Unhandled exception during run
Traceback (most recent call last):
  File "/home/pi/klipper/klippy/klippy.py", line 217, in run
    self.reactor.run()
  File "/home/pi/klipper/klippy/reactor.py", line 292, in run
    g_next.switch()
  File "/home/pi/klipper/klippy/reactor.py", line 347, in _dispatch_loop
    self._fds[fd].read_callback(eventtime)
  File "/home/pi/klipper/klippy/extras/gcode_shell_command.py", line 35, in _process_output
    data = self.partial_output + data
TypeError: can only concatenate str (not "bytes") to str
Transition to shutdown state: Unhandled exception during run```

**Comment by lhndo** [comment]
Thanks for reporting this. It might be an issue with the gcode_shell_command and not the scripts. Those are very basic and should not affect klipper at all.

Did you use gcode_shell_command in other cases before, and did it run successfully? Could you set it up to run a different simple bash script and see if that completes successfully?

**Comment by lhndo** [comment]
I pushed some updates to the bash script. Could you please update the files and try again.

**Comment by bobbleheed** [comment]
Issue appears to have been with standalone installation of code_shell_command.py because I don't use KIAUH.
Running the following solves the issue:
``cd /home/pi/klipper/klippy/extras/``
``wget https://raw.githubusercontent.com/th33xitus/kiauh/master/resources/gcode_shell_command.py``
